# Generated by Django 5.0.2 on 2024-02-18 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webvideo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_video_path', models.FileField(max_length=255, upload_to='mask_videos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='srollervideo',
            name='mask_video_path',
        ),
        migrations.AlterField(
            model_name='srollervideo',
            name='output_video_path',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='output_videos/'),
        ),
        migrations.AddField(
            model_name='srollervideo',
            name='mask_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webvideo.uservideo'),
        ),
    ]
