# Generated by Django 5.0.2 on 2024-02-18 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webvideo', '0002_uservideo_remove_srollervideo_mask_video_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srollervideo',
            name='mask_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webvideo.uservideo'),
        ),
    ]
