# Generated by Django 5.0.2 on 2024-02-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webvideo', '0003_alter_srollervideo_mask_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='srollervideo',
            name='screenshot_path',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='screenshots/'),
        ),
    ]
