# Generated by Django 5.0.2 on 2024-02-21 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webvideo', '0005_uservideoproject_alter_srollervideo_mask_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_video_path', models.FileField(max_length=255, upload_to='mask_videos/')),
            ],
        ),
        migrations.AlterField(
            model_name='srollervideo',
            name='mask_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webvideo.uservideo'),
        ),
        migrations.DeleteModel(
            name='UserVideoProject',
        ),
    ]
