# Generated by Django 5.0.2 on 2024-02-25 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webvideo', '0008_rename_srollervideo_scrollervideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrollervideo',
            name='mask_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webvideo.uservideoproject'),
        ),
    ]
